[package]

name = "selectors"
version = "0.1.0"
authors = ["Simon Sapin <simon.sapin@exyr.org>"]
documentation = "http://doc.servo.org/selectors/"

description = "CSS Selectors matching for Rust"
repository = "https://github.com/servo/rust-selectors"
readme = "README.md"
keywords = ["css", "selectors"]
license = "MPL-2.0"

[features]
unstable = ["string_cache_plugin", "string_cache/unstable"]

[dependencies]
bitflags = "0.3"
matches = "0.1"
cssparser = "0.3"
smallvec = "0.1"
fnv = "1.0"
string_cache = "0.1.10"
string_cache_plugin = { version = "0.1.6", optional = true }
quickersort = "1.0.0"

[dev-dependencies]
rand = "0.3"
